- hosts: k80sadmin
  remote_user: ansadmin
  become: yes
  tasks:
    - name: Download Kubectl binaries
      shell: 'curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
'
    - name: change mode
      shell: 'chmod +x ./kubectl'

    - name: move binaries
      shell: 'sudo mv ./kubectl /usr/local/bin/kubectl'

    - name: install AWSCLI
      shell: ' curl https://s3.amazonaws.com/aws-cli/awscli-bundle.zip -o awscli-bundle.zip'

    - name:  AWS in local
      shell: '  ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws'

    - name: install kops
      shell: 'curl -LO https://github.com/kubernetes/kops/releases/download/$(curl -s https://api.github.com/repos/kubernetes/kops/releases/latest | grep tag_name | cut -d '"' -f 4)/kops-linux-amd64'

    - name: move kops
      shell: ' sudo mv kops-linux-amd64 /usr/local/bin/kops'
